/** Rótulos legíveis das ações registradas na auditoria. */
export const AUDIT_LABEL = {
  'ai.report': 'Gerou relatório com IA',
  'apqr.correct_status': 'Corrigiu etapa de conteúdo',
  'apqr.release_cycle': 'Liberou novo ciclo de revisões',
  'apqr.undo_review': 'Desfez revisão',
  'auth.locked': 'Conta bloqueada por tentativas',
  'auth.password_change': 'Alterou a senha',
  'auth.password_reset': 'Redefiniu a senha',
  'content.create': 'Criou material',
  'content.update': 'Editou material',
  'content.archive': 'Arquivou material',
  'content.unarchive': 'Restaurou material',
  'content.reorder': 'Reordenou materiais',
  'edital.create': 'Criou edital',
  'edital.update': 'Editou edital',
  'edital.archive': 'Arquivou edital',
  'edital.unarchive': 'Restaurou edital',
  'edital.plan_save': 'Salvou Plano Global',
  'edital.subject_create': 'Criou matéria',
  'edital.subject_update': 'Alterou matéria',
  'edital.topics_create': 'Adicionou conteúdos',
  'edital.topic_update': 'Alterou conteúdo',
  'enrollment.create': 'Vinculou aluno a edital',
  'enrollment.archive': 'Desvinculou aluno de edital',
  'enrollment.reactivate': 'Revinculou aluno a edital',
  'file.upload': 'Enviou arquivo',
  'import.v1': 'Importou dados da V1',
  'invite.complete': 'Concluiu cadastro pelo convite',
  'methodology.update': 'Alterou regras do método (nova versão)',
  'platform.enter_tenant': 'Admin ONE UP entrou no ambiente',
  'platform.teacher_invite': 'Gerou convite da professora',
  'platform.tenant_create': 'Criou ambiente',
  'platform.tenant_update': 'Alterou ambiente',
  'platform.user_status': 'Alterou acesso de usuário',
  'report.view': 'Abriu relatório de aluno',
  'student.complete_profile': 'Aluno completou cadastro',
  'student.create': 'Convidou aluno',
  'student.invite_regenerate': 'Gerou novo convite de aluno',
  'student.reset_link': 'Gerou link de nova senha',
  'student.update': 'Alterou dados do aluno',
  'student.view_profile': 'Abriu ficha cadastral do aluno',
  'student.view_xray': 'Abriu Raio-X do aluno',
  'team.assign': 'Atribuiu alunos a monitor',
  'team.create': 'Convidou monitor',
  'tenant.branding': 'Alterou identidade visual',
};
export const ROLE_LABEL = { platform_admin: 'ONE UP', teacher: 'Professora', mentor: 'Monitor', student: 'Aluno' };
export const auditLabel = (a) => AUDIT_LABEL[a] || a;
